version: '3.6'
services:
  sender:
    image: docker.io/jcoliz/mqttsender:local-f2a886f
    deploy:
      replicas: 3
    restart: always
    environment:
      - MQTT__SERVER=mqtt
    depends_on:
      mqtt:
        condition: service_healthy
  