version: '3.6'
services:
  sender:
    image: jcoliz/mqttsender:0.9.1-amd64
    deploy:
      replicas: 3
    restart: always
    environment:
      - MQTT__SERVER=mqtt
    depends_on:
      mqtt:
        condition: service_healthy
  