{
 "title": "All Devices",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Selected Device",
    "query": "from(bucket: \"bucket\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> keyValues(keyColumns: [\"device\"])\r\n|> group()\r\n|> keep(columns: [ \"_value\" ])\r\n|> distinct()"
   }
  ]
 },
 "panels": [
  {
   "title": "Temp $device",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "repeat": "device",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"th\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"${device}\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temp/Humidity $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "repeat": "device",
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"th\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${device}\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Air Quality $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "repeat": "device",
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"${device}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}